### ISSUE TITLE
Récupérer la hiérarchie du Code Civil

### ISSUE THREAD

**Issue by tomapp** [tomapp/legifrance#1]
Il faudrait récupérer, dans l'ordre et en respectant la hiérarchie, les différents titres présents dans le Code Civil.
Il serait bien de récupérer les informations suivantes pour chaque catégorie:
- Son niveau dans la hiérarchie
- Son numéro (Titre 1, Titre 2...)
- Son contenu, donc le titre de la catégorie en elle même
- Sa particule (Quand il y a un BIS par exemple)
- Sa norme, c'est à dire le format de sa numérotation (Chiffre romain, numérique, alphanumérique..) 
- Son parent directe

**Comment by tomapp** [comment]
[La page qui contient les catégories](http://www.legifrance.gouv.fr/affichCode.do?cidTexte=LEGITEXT000006070721&dateTexte=20151111)

**Comment by amichel02** [comment]
Je sais pas si ça te sera utile : 
http://www.legifrance.gouv.fr/Aide/Etablir-un-lien
http://www.legifrance.gouv.fr/Droit-francais/Guide-de-legistique/II.-Etapes-de-l-elaboration-des-textes/2.1.-Regles-generales/2.1.8.-Publication-au-Journal-officiel#ancre12157_0_8

**Comment by tomapp** [comment]
Tu t'avances un peu par rapport au travail actuel, mais c'est pas mal du tout pour la suite! :)

**Comment by tomapp** [comment]
Au vue de la modification qu'apporte #5. Il faudra ajouter un champs "code" pour chaque catégorie pour savoir à quel code il appartient.
