### ISSUE TITLE
Récupération des articles différés

### ISSUE THREAD

**Issue by tomapp** [tomapp/legifrance#19]
Actuellement, j'ignore les articles différés. Sont-il nécessaires ?

[Exemple.](http://www.legifrance.gouv.fr/affichCode.do?idArticle=LEGIARTI000031370007&idSectionTA=LEGISCTA000031370005&cidTexte=LEGITEXT000031366350&dateTexte=20160101)

**Comment by amichel02** [comment]
A priori je dirai "osef"

**Comment by tomapp** [comment]
:+1:
