### ISSUE TITLE
Nettoyer les données

### ISSUE THREAD

**Issue by tomapp** [tomapp/legifrance#27]
Pour nettoyer les données, une solution intéressante est de passer par du javascript et nodeJS.

### Syntaxe ###
ES6 pour la syntaxe (avec Babel.)

### Méthodologie de développement ###
Le TDD sera choisit, pour une raison logique : Les développements agissent sur une base de production.  Il faut donc mocker/tester les développements.
La technologie retenue est Mocha couplé avec Chaï et Babel.
Il serait intéressant d'ajouter un watch dans le package.json : 
```shell
./node_modules/.bin/mocha -R min --compilers js:babel-core/register -w
```

 Chaque nettoyage des données sera considéré comme un recyclage. Ce travail pourra donc être permanent.

**Comment by amichel02** [comment]
La numérotation des articles dépend des divisions des codes, donc attention au reset des numéros à chaque fois.

"un article figurant dans le chapitre III du titre II du livre Ier est nécessairement un article commençant par L.123, suivi d'un tiret et d'une numérotation séquentielle"

**Comment by amichel02** [comment]
"les intitulés des parties, livres, titres ou chapitres n'ont pas de portée juridique" => donc pas pertinent du tout !

**Comment by amichel02** [comment]
On ne se préoccupe pas des parties réglementaires (articles R et D).
