### ISSUE TITLE
Critères de mise en avant pour les datamart

### ISSUE THREAD

**Issue by amichel02** [tomapp/legifrance#3]
Qu'est-ce qui doit ressortir de nos données ?

En Droit, quand tu cherches une info, tu cherches toujours deux choses : un article qui correspond à une situation juridique.

A partir c'est pas compliqué : les articles sont dans des codes. Les codes sont divisés en thèmes. Les thèmes traitent d'une situation.

Quid des lois ? Les lois, c'est des bouts de papier sur lesquels les députés ont mis tout ce qui change dans un code. Donc, en vrai, les lois, on s'en fiche car ça ne nous donne aucune information concrète, on sait juste qu'il y a eu du changement.

**Comment by tomapp** [comment]
Donc, si j'ai bien compris, tu estimes qu'en droit, il serait intéressant d'avoir des articles et pas des lois? C'est ça? Je ne saisis pas bien la différence entre les deux dans ce cas.

**Comment by amichel02** [comment]
Une loi, c'est un ensemble de mesures qui modifient la législation.
Un article, c'est un morceau de la législation.

**Comment by tomapp** [comment]
Ok, donc récupérer les articles des différents code classer par "catégories" et par "code" ça serait intéressant déjà?

**Comment by amichel02** [comment]
oui

**Comment by tomapp** [comment]
Ok ça marche, ça change pas mal le principe de récupération que j'ai actuellement qui ne prend en compte que le code civil. Par contre j'ai peur de la quantité de données que je vais récupérer si je passe sur tous les codes... Il faudrait limiter je pense?

**Comment by amichel02** [comment]
bah fais code par code. Un datamart par code. Voire un datamart par thème de code. Je parle en termes de finalité là bien entendu, dans le DWH t'auras tout pêle-mêle.

**Comment by tomapp** [comment]
:+1:
